In [44]:
#Step 1: Import libraries and create alias for Pandas, Numpy etc

In [45]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB 
from sklearn.metrics import precision_score, confusion_matrix, accuracy_score, recall_score

In [ ]:
# Load the dataset

In [3]:
df = pd.read_csv("/home/swaraj/Downloads/archive (1)/iris.csv")
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
# here we print number of rows
df.shape[0]

150

In [6]:
# here we print number of columns
df.shape[1]

5

In [7]:
# checking for missing values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [9]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [ ]:
# Normalizing the data

In [10]:
df['Normalized_sepal_length'] = (df['sepal_length']- df['sepal_length'].min()) / (df['sepal_length'].max() - df['sepal_length'].min())
df['Normalized_sepal_width'] = (df['sepal_width']- df['sepal_width'].min()) / (df['sepal_width'].max() - df['sepal_width'].min())
df['Normalized_petal_length'] = (df['petal_length']- df['petal_length'].min()) / (df['petal_length'].max() - df['petal_length'].min())
df['Normalized_petal_width'] = (df['petal_width']- df['petal_width'].min()) / (df['petal_width'].max() - df['petal_width'].min())

In [ ]:
# converting the catogerical data into numerical

In [11]:
df['Species_Numeric'] = df['species'].replace({
    'setosa': 0,
    'versicolor': 1,
    'virginica': 2
})

/tmp/ipykernel_7597/2807694193.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Species_Numeric'] = df['species'].replace({

In [ ]:
# Drop the species column which is in form of string

In [23]:
df = df.drop(['species'], axis=1)

In [ ]:
# Divide the dataset into independent(X) and dependent(y) variables.

In [24]:
X = df.drop(['Species_Numeric'], axis=1) 
y = df['Species_Numeric']

In [25]:
X

,sepal_length,sepal_width,petal_length,petal_width,Normalized_sepal_length,Normalized_sepal_width,Normalized_petal_length,Normalized_petal_width
0,5.1,3.5,1.4,0.2,0.222222,0.625000,0.067797,0.041667
1,4.9,3.0,1.4,0.2,0.166667,0.416667,0.067797,0.041667
2,4.7,3.2,1.3,0.2,0.111111,0.500000,0.050847,0.041667
3,4.6,3.1,1.5,0.2,0.083333,0.458333,0.084746,0.041667
4,5.0,3.6,1.4,0.2,0.194444,0.666667,0.067797,0.041667
...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,0.666667,0.416667,0.711864,0.916667
146,6.3,2.5,5.0,1.9,0.555556,0.208333,0.677966,0.750000
147,6.5,3.0,5.2,2.0,0.611111,0.416667,0.711864,0.791667
148,6.2,3.4,5.4,2.3,0.527778,0.583333,0.745763,0.916667
149,5.9,3.0,5.1,1.8,0.444444,0.416667,0.694915,0.708333

In [26]:
y

0      0
1      0
2      0
3      0
4      0
      ..
145    2
146    2
147    2
148    2
149    2
Name: Species_Numeric, Length: 150, dtype: int64

In [ ]:
# Split the dataset into training and testing datasets

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=42)

In [ ]:
# Use Naive Bayes algorithm

In [28]:
gaussian = GaussianNB()
gaussian.fit(X_train, y_train)

GaussianNB()

In [ ]:
# Predict the y_pred for all values of X_train & X_test

In [29]:
Y_pred = gaussian.predict(X_test)

In [31]:
Y_pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [ ]:
# Evaluate the performance of Model for y_train and y_test

In [38]:
accuracy = accuracy_score(y_test,Y_pred)
accuracy

1.0

In [41]:
ps = precision_score(y_test, Y_pred, average = 'micro')
ps

1.0

In [42]:
recall = recall_score(y_test, Y_pred, average = 'micro')
recall

1.0

In [43]:
cm = confusion_matrix(y_test, Y_pred)
cm

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])